name: Start test and build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run C++ tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install g++ cmake libgtest-dev

      - name: Build and run tests
        run: |
          make test_base
          make test_bot
          make test_game
          make clean

  build:
    name: build all project
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install g++ cmake libgtest-dev

      - name: Build project
        run: make
