on:Add commentMore actions
  push:
    branches:
      - MainBranchForAllProject
  pull_request:
    branches:
      - MainBranchForAllProject


jobs:
  test:
    name: Run C++ tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        
      - name: Install dependencies
        run: sudo apt-get install g++ cmake libgtest-dev libasound2-dev
        
      - name: Build and run tests
        run: |
          make test_base
          make test_bot
          make test_game
          make test_char
          make test_mode
          make clean

  build:
@@ -53,7 +48,13 @@ jobs:
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install g++ cmake libgtest-dev libasound2-dev

      - name: Build project
        run: make
        run: |
          make
          make clean
